### ISSUE TITLE
Kotlinize dynamic-links, firebaseoptions, storage and tasks

### ISSUE THREAD

**Issue by rosariopfernandes** [firebase/snippets-android#24]
I saw #5 and #12 and the resulting Kotlin Activities (looks great btw). So I was wondering if I could do the same for the [dynamic-links](https://github.com/firebase/snippets-android/tree/master/dynamic-links), [firebaseoptions](https://github.com/firebase/snippets-android/tree/master/firebaseoptions), [storage](https://github.com/firebase/snippets-android/tree/master/storage) and [tasks](https://github.com/firebase/snippets-android/tree/master/tasks) code snippets.
Just let me know and I'll start working on a PR

**Comment by samtstern** [comment]
@rosariopfernandes thanks for the offer!  I'd love to get Kotlin contributions for those samples, and I'd happily review the PRs. 

Before you start though, some notes:

- Please keep the PRs small so that they're easy to review, so maybe just one module at a time.
- We are currently working through some issues with generating Kotlin reference docs.  We want to get ref docs published before we add the Kotlin snippets to the documentation guides.  So while developers will be able to look at this repo and learn from your code, it could be a while before you see it in the main documentation. It's because of our technical issues, not because we don't appreciate your effort!

**Comment by rosariopfernandes** [comment]
Thank you  @samtstern ! Understood, I'll send small PRs with one module at a time.

**Comment by samtstern** [comment]
@rosariopfernandes thank you so much for the quick and high-quality work!

**Comment by rosariopfernandes** [comment]
It was my pleasure. Always glad to contribute to the Firebase Community! :) 

Good Luck for the team working on the KDocs issue! Can't wait to see the Kotlin ref docs on the site.
