### ISSUE TITLE
viewBinding Update Code

### ISSUE THREAD

**Issue by AryanBisht-03** [firebase/snippets-android#289]
We can use viewBinding in the code which is updated version and also recommended by the Google.
So please update the code

**Comment by samtstern** [comment]
@AryanBisht-03 are there some specific snippets you'd like to see updated?

**Comment by rosariopfernandes** [comment]
I agree we should remove the deprecated `kotlin-android-extensions` plugin, but since this repo only contains snippets and these apps aren't supposed to run on an actual device or emulator, maybe we don't really need viewbinding? We could stick to findViewById, unless there's a `findViewById()` exposed somewhere in the snippets.

**Comment by samtstern** [comment]
@rosariopfernandes yeah I'm only concerned about the code that's exposed in the docs, if we use `findViewById()` in supporting/excluded code that's fine for this repo.
